version: '3.4'

services:
  indexer:
    build:
      context: .
      dockerfile: ./Meilidown.Indexer/Dockerfile
    environment:
      - Meilisearch__Url=http://meilisearch:${MEILISEARCH_PORT:-7700}
      - Meilisearch__ApiKey=${MEILISEARCH_API_KEY:-masterKey}
      - FileApi__Image=${API_FRONT:-https://localhost}/Image/{0}
    depends_on:
      - meilisearch
    volumes:
      - appsettings.local.json:/app/appsettings.local.json
  api:
    build:
      context: .
      dockerfile: ./Meilidown.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
      - Meilisearch__Url=http://meilisearch:${MEILISEARCH_PORT:-7700}
      - Meilisearch__ApiKey=${MEILISEARCH_API_KEY:-masterKey}
    ports:
      - "${API_PORT:-443}:443"
    depends_on:
      - meilisearch
      - indexer
    volumes:
      - appsettings.local.json:/app/appsettings.local.json
  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "${MEILISEARCH_PORT:-7700}:7700"
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_API_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./data:/data